[platformio]
default_envs = ghostble

[env:ghostble]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = m5stack-cardputer
framework = arduino

build_flags = 
    -DCARDPUTER
    -I src

monitor_speed = 115200

lib_deps =
    m5stack/M5Cardputer
    m5stack/M5Unified
    h2zero/NimBLE-Arduino
    mathieucarbou/AsyncTCP@^3.2.14
    mathieucarbou/ESPAsyncWebServer@^3.4.5
    mikalhart/TinyGPSPlus

[env:native]
platform = native
test_framework = googletest
build_flags = -std=gnu++17

build_src_filter = -<*>
