[env:ghostble]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = m5stack-cardputer
framework = arduino

board_build.variant = esp32s3

build_flags = -DCARDPUTER

monitor_speed = 115200

lib_deps =
    m5stack/M5Cardputer
    m5stack/M5Unified
    h2zero/NimBLE-Arduino
    mathieucarbou/AsyncTCP@^3.2.14
    mathieucarbou/ESPAsyncWebServer@^3.4.5
    mikalhart/TinyGPSPlus

[env:ghostble-stickcplus2]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = m5stack-stickcplus2
framework = arduino

build_flags = -DM5STICKCPLUS2

monitor_speed = 115200

lib_deps =
    m5stack/M5StickCPlus2
    m5stack/M5Unified
    h2zero/NimBLE-Arduino
    mathieucarbou/AsyncTCP@^3.2.14
    mathieucarbou/ESPAsyncWebServer@^3.4.5
    mikalhart/TinyGPSPlus

[env:ghostble-sticks3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = m5stack-sticks3
framework = arduino

board_build.variant = esp32s3

build_flags = -DM5STICKS3

monitor_speed = 115200

lib_deps =
    m5stack/M5Unified
    h2zero/NimBLE-Arduino
    mathieucarbou/AsyncTCP@^3.2.14
    mathieucarbou/ESPAsyncWebServer@^3.4.5
    mikalhart/TinyGPSPlus
