[env:ghostble]
platform = espressif32@6.9.0
board = m5stack-cardputer
framework = arduino

monitor_speed = 115200

lib_deps =
    m5stack/M5Cardputer
    m5stack/M5Unified
    h2zero/NimBLE-Arduino
    mathieucarbou/AsyncTCP@^3.2.14
    mathieucarbou/ESPAsyncWebServer@^3.4.5
    mikalhart/TinyGPSPlus
