#include "ManufacturerHelper.h"

String getManufacturerName(uint16_t manufacturerId) {
    if (manufacturerId == 0x2E5) return "Espressif Systems (M5Stack)";
    if (manufacturerId == 0x4C) return "Apple, Inc.";
    if (manufacturerId == 0x6) return "Microsoft Corporation";
    if (manufacturerId == 0xF) return "Broadcom Corporation";
    if (manufacturerId == 0x131) return "Google";
    if (manufacturerId == 0x75) return "Samsung Electronics Co.";
    if (manufacturerId == 0x05A7) return "Samsung Electronics Co. Ltd.";
    if (manufacturerId == 0xE0) return "Nintendo Co., Ltd.";
    if (manufacturerId == 0x1) return "Ericsson Technology Licensing";
    if (manufacturerId == 0x2) return "Intel Corp.";
    if (manufacturerId == 0x3) return "IBM Corp.";
    if (manufacturerId == 0x4) return "Toshiba Corp.";
    if (manufacturerId == 0x5) return "3Com";
    if (manufacturerId == 0x12) return "Matsushita Electric Industrial Co.";
    if (manufacturerId == 0x1D) return "Motorola";
    if (manufacturerId == 0x25) return "Nokia Mobile Phones";
    if (manufacturerId == 0x3D) return "Hitachi, Ltd";
    if (manufacturerId == 0x65) return "Sony Ericsson Mobile Communications";
    if (manufacturerId == 0x79) return "LG Electronics";
    if (manufacturerId == 0xA0) return "Qualcomm Inc.";
    if (manufacturerId == 0xC7) return "Garmin International, Inc.";
    if (manufacturerId == 0xD2) return "GoPro, Inc.";
    if (manufacturerId == 0xE1) return "Bosch Sensortec GmbH";
    if (manufacturerId == 0xEC) return "Sony Corporation";
    if (manufacturerId == 0x106) return "Tile, Inc.";
    if (manufacturerId == 0x110) return "Fitbit, Inc.";
    if (manufacturerId == 0x12D) return "Signify (Philips Lighting B.V.)";
    if (manufacturerId == 0x133) return "Facebook Technologies, LLC";
    if (manufacturerId == 0x165) return "Xiaomi Inc.";
    if (manufacturerId == 0x171) return "OPPO Mobile Telecommunications Corp.";
    if (manufacturerId == 0x17C) return "Huawei Technologies Co., Ltd.";
    if (manufacturerId == 0x18B) return "vivo Mobile Communication Co., Ltd.";
    if (manufacturerId == 0x195) return "OnePlus Electronics Corp.";
    if (manufacturerId == 0x0ECB) return "Zhong Shan City Richsound Electronic Industrial Ltd";
    if (manufacturerId == 0x57) return "Harman International Industries, Inc";
    if (manufacturerId == 0x7F) return "Lenovo";
    if (manufacturerId == 0x1A6) return "Realme Mobile Telecommunications";
    if (manufacturerId == 0x1D6) return "Anker Innovations Limited";
    if (manufacturerId == 0x1E3) return "Amazfit (Huami)";
    if (manufacturerId == 0x1DC) return "Wyze Labs, Inc.";
    if (manufacturerId == 0xE7) return "Polar Electro Oy (Heart rate devices!)";
    if (manufacturerId == 0x6b) return "Polar Electro Oy";
    if (manufacturerId == 0xC3) return "Bose Corporation"; 
    if (manufacturerId == 0xAF) return "Plantronics (now Poly)";
    if (manufacturerId == 0x30) return "Symbol Technologies (barcode scanners)";
    if (manufacturerId == 0x3FF) return "Withings (Unofficial)";
    return "Unknown Manufacturer";
}
