name: Build Firmware

on:
  release:
    types: [published]
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install platformio esptool

      # Build firmware
      - name: Build
        run: pio run

      # Detect build folder dynamically
      - name: Get build path
        run: |
          BUILD_DIR=$(ls -d .pio/build/* | head -n 1)
          echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV

      # Merge binaries (M5Burner compatible)
      - name: Merge binaries
        run: |
          if [ -f "$BUILD_DIR/boot_app0.bin" ]; then
            echo "Using boot_app0.bin"
            python -m esptool --chip esp32s3 merge-bin -o merged.bin \
              --flash-mode dio \
              --flash-freq 40m \
              --flash-size 8MB \
              0x0 $BUILD_DIR/bootloader.bin \
              0x8000 $BUILD_DIR/partitions.bin \
              0xE000 $BUILD_DIR/boot_app0.bin \
              0x10000 $BUILD_DIR/firmware.bin
          else
            echo "boot_app0.bin NOT found → building without it"
            python -m esptool --chip esp32s3 merge-bin -o merged.bin \
              --flash-mode dio \
              --flash-freq 40m \
              --flash-size 8MB \
              0x0 $BUILD_DIR/bootloader.bin \
              0x8000 $BUILD_DIR/partitions.bin \
              0x10000 $BUILD_DIR/firmware.bin
          fi

      # Rename with version
      - name: Rename merged binary
        run: |
          VERSION=${{ github.event.release.tag_name }}
          mv merged.bin GhostBLE-${VERSION}.bin

      # Upload to GitHub Release
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            GhostBLE-*.bin
            ${{ env.BUILD_DIR }}/firmware.bin
            ${{ env.BUILD_DIR }}/bootloader.bin
            ${{ env.BUILD_DIR }}/partitions.bin
            ${{ env.BUILD_DIR }}/boot_app0.bin
